#!/usr/bin/env python3
"""Build a standalone receiver from notify without distributing sender code."""

import ast
from pathlib import Path
import sys


RECEIVER_NAMES = {
    "PORT", "MAX_BODY", "CLOCK_WINDOW", "IO_TIMEOUT",
    "config_dir", "read_key", "validate_message", "show_popup", "signature",
    "NotifyServer", "NotifyHandler", "desktop_available", "listen",
    "desktop_quote", "autostart", "port_number", "receiver_main",
}
RECEIVER_IMPORTS = {
    "argparse", "hashlib", "hmac", "html", "json", "os", "pathlib", "re",
    "shutil", "subprocess", "sys", "threading", "time", "http.server",
}


def build_receiver():
    source = Path(__file__).with_name("notify").read_text(encoding="utf-8")
    lines = source.splitlines(keepends=True)
    sections = [
        '#!/usr/bin/env python3\n"""Receive desktop notifications only. Generated by build_receiver.py."""\n',
    ]
    found = set()
    for node in ast.parse(source).body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            modules = {alias.name for alias in node.names} if isinstance(node, ast.Import) else {node.module}
            include = modules <= RECEIVER_IMPORTS
        else:
            names = {node.name} if isinstance(node, (ast.FunctionDef, ast.ClassDef)) else set()
            if isinstance(node, ast.Assign):
                names = {target.id for target in node.targets if isinstance(target, ast.Name)}
            include = bool(names) and names <= RECEIVER_NAMES
            if include:
                found.update(names)
        if include:
            sections.append("".join(lines[node.lineno - 1:node.end_lineno]).rstrip() + "\n")
    missing = RECEIVER_NAMES - found
    if missing:
        raise ValueError("Receiver definitions missing: " + ", ".join(sorted(missing)))
    sections.append('if __name__ == "__main__":\n    sys.exit(receiver_main())\n')
    return "\n\n".join(sections)


if __name__ == "__main__":
    sys.stdout.write(build_receiver())
